### ISSUE TITLE
toggle funksjonaliteten  om søkefelt skal vises fungerer ikke

### ISSUE THREAD

**Issue by Havardmj** [navikt/internarbeidsflatedecorator#85]
interface Toggles {
    visVeilder: boolean;
    visSokefelt: boolean; // selv om denne settes til false, vises fortsatt søkefeltet i menyen
    visEnhetVelger: boolean;
    visEnhet: boolean;
}

**Comment by nutgaard** [comment]
PR som løser problemet ble laget 18.02 12:11: #84 
Venter bare på godkjenning av de som står som reviewers.
